import { AppShell } from "@/components/app-shell";
import { Panel, SectionTitle } from "@/components/ui";

export default function ReportsPage() {
  const reports = [["Growth Diagnostics – May 2025", "May 20, 2025", "PDF"], ["Experiment Results – Hook Test", "May 12, 2025", "CSV"], ["Audit Log – Carousel Review", "May 11, 2025", "MD"]];
  return <AppShell title="Export Report" eyebrow="" subtitle="Prepare your workspace report for sharing or archiving.">
    <Panel className="export-form"><label><span>Report Name</span><input defaultValue="Growth Diagnostics – May 2025" /></label><fieldset><legend>Export Format</legend><div className="format-grid"><label><input type="radio" name="format" defaultChecked /><span><b>PDF</b><small>A print-ready document with audit findings and visual summaries.</small></span></label><label><input type="radio" name="format" /><span><b>CSV</b><small>Raw data for analysis, audits, and experiment results.</small></span></label><label><input type="radio" name="format" /><span><b>Markdown</b><small>A lightweight text export for notes and summaries.</small></span></label></div></fieldset><fieldset><legend>Export Scope</legend><label className="check"><input type="checkbox" defaultChecked /> Include Audit Results</label><label className="check"><input type="checkbox" defaultChecked /> Include 7-Day Growth Plan</label><label className="check"><input type="checkbox" /> Include Experiment Results</label></fieldset><div className="privacy-note">PRIVACY & SECURITY<br /><span>Only the selected analytics is exported. Your data stays private and protected.</span></div><div className="form-actions"><button className="button primary">Download Report</button><button className="button ghost">Copy to Clipboard</button></div></Panel>
    <Panel><SectionTitle eyebrow="" title="Recent Exports" /><ul className="plain-list exports">{reports.map(([title, date, format]) => <li key={title}><span><b>{title}</b><small>{date}</small></span><em>{format} &nbsp; Re-download</em></li>)}</ul></Panel>
    <SectionTitle eyebrow="" title="State Variants" /><div className="metric-grid three state-grid"><Panel><span>LOADING</span><p>Generating report…</p><div className="track"><i style={{ width: "65%" }} /></div></Panel><Panel><span>SUCCESS</span><p>Report downloaded successfully.</p><a href="#">Download Again</a></Panel><Panel><span>ERROR</span><p>Export failed – please try again.</p><button className="button primary">Retry</button></Panel></div>
  </AppShell>;
}
